options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000

defaults:
  dcf: "mcDSA_4000.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: true
  period: 10
  scale_pos_to_dev: 3395.30545263 # 32000*24/36/2/pi
  scale_pos_from_dev: 0.00029452431
  scale_vel_to_dev: 2037.17850777 # 320/36*24*60/2/pi 320 to 1rpm on motor side, 36/24 - reduction -> rpm to rad/s
  scale_vel_from_dev: 0.00049087499
  position_mode: 1
  velocity_mode: 2
  switching_state: 2
  # heartbeat_producer: 1000 # Heartbeat every 1000 ms
  sdo: # SDO executed during config
    - {index: 0x4303, sub_index: 1, value: 10}            #vel scale denominator
    - {index: 0x6081, sub_index: 0, value: 100}          # Velocity [rpm]
    - {index: 0x6089, sub_index: 0, value: -3}          
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}       # Status word
        - {index: 0x6061, sub_index: 0}       # Modes of operation display 
        - {index: 0x6064, sub_index: 0}       # Position - actual value
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x4A04, sub_index: 2}       # Measured velocity in [rpm]
        - {index: 0x6077, sub_index: 0}       # Torque - actual value
  rpdo: 
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}       # Control word
        - {index: 0x6060, sub_index: 0}       # Modes of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x607A, sub_index: 0}         # Target position
      - {index: 0x6042, sub_index: 0}         # Target velocity
      - {index: 0x6071, sub_index: 0}         # Target torque

nodes:
  left_wheel_motor:
    node_id: 2
  right_wheel_motor:
    node_id: 3